services:
  web:
    image: python:3.12-slim
    working_dir: /app
    command: sh -c "pip install --upgrade pip && pip install -r requirements.txt && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env

  temporal_workers:
    image: python:3.12-slim
    working_dir: /app
    command: sh -c "pip install --upgrade pip && pip install -r requirements.txt && python -m ExtractInfo.temporal_workers"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    depends_on:
      - web
